"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { ArrowUpRight, GitBranch, RefreshCw } from "lucide-react";
import AppShell from "@/components/AppShell";
import CopyButton from "@/components/CopyButton";
import { getAdmittedHead, getAdmittedHistory, getPolicy, type PolicyRecord } from "@/lib/contracts";

export default function Page() {
  const { policyKey } = useParams<{ policyKey: string }>(); const [policy,setPolicy]=useState<PolicyRecord|null>(null); const [head,setHead]=useState(""); const [history,setHistory]=useState<Array<Record<string,unknown>>>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  async function load() { setLoading(true); setError(""); try { const record=await getPolicy(decodeURIComponent(policyKey));setPolicy(record);if(record){const [current,entries]=await Promise.all([getAdmittedHead(record.lineage_key),getAdmittedHistory(record.lineage_key)]);setHead(current);setHistory(entries);} } catch(e) { setError(e instanceof Error?e.message:String(e)); } finally { setLoading(false); } }
  useEffect(()=>{void load();},[policyKey]);
  return <AppShell>{error?<div className="error" role="alert">Could not read this policy from finalized contract state: {error}</div>:loading?<div className="empty-state">Reading frozen policy and admitted lineage…</div>:!policy?<div className="empty-state">No policy with key <code>{policyKey}</code> exists in finalized contract state.</div>:<>
    <div className="dossier-overline"><Link href="/">Lineages</Link><span>/</span><span>Policy revision</span><span>/</span><code>{policy.policy_key}</code></div>
    <section className="policy-hero"><div className="policy-revision-glyph"><GitBranch size={20}/><span>REV {String(policy.version).padStart(2,"0")}</span></div><div className="policy-title"><div className="eyebrow"><span className="eyebrow-line"/> FROZEN POLICY REVISION</div><h1>{policy.software_name}</h1><p>{policy.repository_owner}/{policy.repository_name}</p></div><button className="icon-label-button refresh-policy" onClick={()=>void load()}><RefreshCw size={15}/> Refresh finalized state</button></section>
    <section className="policy-stamp"><div><span className="revision-stamp">IMMUTABLE REVISION</span><strong>Policy v{policy.version}</strong><small>Published terms remain inspectable after successor revisions.</small></div><div className="policy-digest"><span>POLICY DIGEST</span><code>{policy.policy_digest}</code><CopyButton value={policy.policy_digest}/></div></section>
    <div className="policy-facts"><div><small>SOFTWARE LINEAGE</small><code>{policy.lineage_key}</code><CopyButton value={policy.lineage_key}/></div><div><small>ADMITTED HEAD</small><code>{head||"Genesis · no admitted release"}</code>{head?<CopyButton value={head}/>:null}</div><div><small>PREDECESSOR REVISION</small><code>{policy.predecessor_policy_key||"First revision"}</code></div><div><small>POLICY ADOPTER</small><code>{policy.owner}</code></div><div><small>DESIGNATED PUBLISHER</small><code>{policy.publisher??policy.owner}</code></div></div>
    <div className="actions policy-actions"><Link className="button" href={`/release/new?policy=${encodeURIComponent(policy.policy_key)}`}>Evaluate a release <ArrowUpRight size={15}/></Link><Link className="button secondary" href="/policy/new">Create successor policy <ArrowUpRight size={15}/></Link></div>
    <section className="policy-section"><div className="section-heading"><div><span className="section-kicker">01 / INTENDED USE</span><h2>Context and admission boundary.</h2></div></div><div className="policy-prose"><div><small>USAGE CONTEXT</small><p>{policy.usage_context}</p></div><div><small>ADMISSION POLICY</small><p>{policy.admission_policy}</p></div></div></section>
    <section className="policy-section"><div className="section-heading"><div><span className="section-kicker">02 / FROZEN CRITERIA</span><h2>What the release must establish.</h2></div><span className="section-side-note">{policy.criteria.length} criterion {policy.criteria.length===1?"rule":"rules"}</span></div><div className="policy-criteria">{policy.criteria.map((criterion,index)=><article className="policy-criterion" key={criterion.id}><span className="matrix-index">{String(index+1).padStart(2,"0")}</span><div><code>{criterion.id}</code><h3>{criterion.title}</h3><p>{criterion.rule}</p></div><span className="criterion-rail"/></article>)}</div></section>
    <section className="policy-section"><div className="section-heading"><div><span className="section-kicker">03 / ROLE-BOUND SOURCES</span><h2>Accepted authority scopes.</h2></div></div><div className="authority-table">{policy.required_roles.map((role,index)=><article className="authority-table-row" key={role}><span className="matrix-index">{String(index+1).padStart(2,"0")}</span><div><b>{role.replaceAll("_"," ")}</b><small>REQUIRED EVIDENCE ROLE</small></div><div className="authority-scopes">{(policy.evidence_authorities[role]??[]).map(scope=><code key={scope.host+scope.path_prefix}><span>https://</span>{scope.host}{scope.path_prefix}</code>)}<small>ISSUER: {policy.evidence_issuers?.[role]??"No wallet attestation required"}</small></div></article>)}</div><p>Issuer wallets are designated by this policy's adopter. Distinct addresses alone do not establish independently controlled organizations.</p></section>
    <section className="policy-section"><div className="section-heading"><div><span className="section-kicker">04 / ADMITTED LINEAGE</span><h2>Finalized release progression.</h2></div></div>{history.length?<div className="policy-lineage">{history.map((entry,index)=><Link className="policy-lineage-row" href={`/release/${encodeURIComponent(String(entry.candidate_key??""))}`} key={String(entry.candidate_key??index)}><span className="release-track-node"><i/></span><div><small>ADMITTED RELEASE {String(index+1).padStart(2,"0")}</small><strong>{String(entry.release_label??entry.candidate_key??"release")}</strong><code>{String(entry.commit_sha??"")}</code></div><span className="lineage-current">{String(entry.candidate_key??"")===head?"CURRENT HEAD":"FINALIZED"}</span><ArrowUpRight size={15}/></Link>)}</div>:<div className="lineage-empty compact"><div className="empty-node"/><span>No release has advanced this line.</span><small>Uncertain and rejected attempts remain in their release dossiers.</small></div>}</section>
  </>}</AppShell>;
}
